name: "Blog of Devin Shen"
description: "Web Back-End Blog by Devin Shen"

url: "http://shenjl.github.io/blog"
loadingImg: "http://shenjl.github.io/blog/img/loading.gif"
filePath: "http://shenjl.github.io/blog/img/"

timezone: Asia/Shanghai

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

plugins:
- jekyll-paginate
port: 4002